plugins = []
headers = []
redirects = []

[database]

  [database.migrations]
  path = "/opt/build/repo/netlify/database/migrations"

[build]
publish = "/opt/build/repo/dist/client"
publishOrigin = "config"
commandOrigin = "config"
command = "vite build"

  [build.environment]

  [build.processing]

    [build.processing.css]

    [build.processing.html]

    [build.processing.images]

    [build.processing.js]

  [build.services]

[dev]
command = "npm run dev"
targetPort = 3000
port = 8888

[functions]

  [functions."*"]